### ISSUE TITLE
alipay open api 

### ISSUE THREAD

**Issue by fengmk2** [node-modules/ali-sdk#10]
https://open.alipay.com/index.htm

**Comment by JacksonTian** [comment]
我来接手这个吧。 微信公共号的API都写过一遍了。

**Comment by JacksonTian** [comment]
不过这下面要细分下。alipass，公共号，alipayinside等。

**Comment by fengmk2** [comment]
只做对外的，对内的不做。

哈哈，可以先做阿里云的 service。

**Comment by fengmk2** [comment]
@JacksonTian 你没有接受团队邀请，assign 不了给你。。。

**Comment by JacksonTian** [comment]
可能错过邮件了。现在加入了。

**Comment by fengmk2** [comment]
可以先看 https://github.com/ali-sdk/ali-sdk/wiki
