### ISSUE TITLE
aliexpress open api 

### ISSUE THREAD

**Issue by fengmk2** [node-modules/ali-sdk#11]
http://open.aliexpress.com/

**Comment by gxcsoccer** [comment]
我认领 alibaba 和 aliexpress 的

**Comment by fengmk2** [comment]
@gxcsoccer 邀请你了。

哈哈，其实有空可以先做 aliyun 的

**Comment by gxcsoccer** [comment]
aliyun的你们是怎么做的？参考其他语言的sdk？

**Comment by fengmk2** [comment]
不参考，自己想怎么写才是最符合开发者使用的。你可以看看 ali-oss

**Comment by fengmk2** [comment]
阿里云现在的那个 oss 客户端就是参考 aws 的。。。你看了都不会想去用。

**Comment by gxcsoccer** [comment]
明白了

**Comment by z112389089** [comment]
请问下有api获取订单数据的例子代码吗？

**Comment by Ruijie-Zhang** [comment]
aliexpress 的Open API的问题，有沟通的mail地址吗？ 这个Java SDK，http://g01.a.alicdn.com/kf/HTB1qYDWKXXXXXX6XFXXM7NXFXXXg.zip

**Comment by hadijahangiri** [comment]
Aliexpress have a .Net SDK?

**Comment by webuy17** [comment]
hello someone know how to get api keys ??
