### ISSUE TITLE
Work flow

### ISSUE THREAD

**Issue by fengmk2** [node-modules/ali-sdk#8]
https://github.com/node-modules/ali-sdk/wiki#work-flow

Everyone read this before action.

**Comment by fengmk2** [comment]
@ali-sdk/owners please join https://cnode.slack.com/ first

**Comment by popomore** [comment]
放 repo 里好了

**Comment by luckydrq** [comment]
@fengmk2 how to join [https://cnode.slack.com/](https://cnode.slack.com/)? I don't know to use which account.

**Comment by fengmk2** [comment]
Give me your personal email

**Comment by luckydrq** [comment]
@fengmk2  drqzju@gmail.com, thanks!

**Comment by fengmk2** [comment]
@luckydrq sent! check you email box.

**Comment by luckydrq** [comment]
I'm in :hand:
