### ISSUE TITLE
MQS Usage

### ISSUE THREAD

**Issue by fengmk2** [node-modules/ali-sdk#9]
MQS account get!

http://mqs.console.aliyun.com/?spm=0.0.0.0.jHvUGw#/list/cn-hangzhou

**Comment by gxcsoccer** [comment]
那我认领这个吧，哈哈 @fengmk2

**Comment by fengmk2** [comment]
这个我已经在写了。。。我连 MQS 服务也申请了。。。准备用到 cnpm 上。

哈哈，再挑一个。

**Comment by gxcsoccer** [comment]
现在还有那些，你排个优先级

**Comment by fengmk2** [comment]
你去 readme 上看，你对那个有兴趣

**Comment by gxcsoccer** [comment]
KVStore 那个有人做吗，是说api follow thunk-redis, 然后等人实现是吧？

**Comment by gxcsoccer** [comment]
好像，直接可以用thunk-redis。。。

**Comment by fengmk2** [comment]
kvstore 没有，是可以使用，但是也得包装的，你看看 ali-rds

**Comment by dead-horse** [comment]
thunk-redis 靠谱么？

**Comment by fengmk2** [comment]
有严老师在维护，靠谱的

**Comment by gxcsoccer** [comment]
好吧，我搞个偏的 MTS，哈哈
